#!/usr/bin/env python3
"""Build the bundled registration-plate visual from its STL (standard library only).

python scripts/build_plate_visual.py "NEBIUSSR101_ORCHID PLATE V2.stl"
Reduces the mesh for display (vertex clustering, like build_so101_visuals.py) and writes
orchid_demo/static/plate-visual.js with the follower mounts and Orchid pocket from orchid_demo/layout.py.
Display only: never collision geometry. Never run by the app.
"""
import argparse
from collections import defaultdict
import json
from pathlib import Path
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from orchid_demo import layout  # noqa: E402

CELL_MM = 1.0


def reduce(data):
    count = struct.unpack_from("<I", data, 80)[0]
    if len(data) != 84 + count * 50:
        raise ValueError("Expected a binary STL")
    buckets, triangles, seen = defaultdict(list), [], set()
    faces = []
    for offset in range(84, len(data), 50):
        coords = struct.unpack_from("<9f", data, offset + 12)
        face = []
        for i in (0, 3, 6):
            vertex = coords[i:i + 3]
            key = tuple(round(x / CELL_MM) for x in vertex)
            buckets[key].append(vertex)
            face.append(key)
        faces.append(face)
    index = {key: n for n, key in enumerate(buckets)}
    # vertices in units of 10 micrometres, like arm-visuals.js (vertex_scale 1e-5 m)
    vertices = [round(sum(v[a] for v in points) / len(points) * 100) for points in buckets.values() for a in range(3)]
    for face in faces:
        f = tuple(index[k] for k in face)
        key = tuple(sorted(f))
        if len(set(f)) == 3 and key not in seen:
            seen.add(key)
            triangles.extend(f)
    xs, ys, zs = vertices[0::3], vertices[1::3], vertices[2::3]
    bounds = [[min(xs) / 1e5, min(ys) / 1e5, min(zs) / 1e5], [max(xs) / 1e5, max(ys) / 1e5, max(zs) / 1e5]]
    return {"vertices": vertices, "triangles": triangles, "bounds": bounds, "source_triangles": count}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stl", type=Path)
    parser.add_argument("--output", type=Path, default=Path("orchid_demo/static/plate-visual.js"))
    args = parser.parse_args()
    mesh = reduce(args.stl.read_bytes())
    payload = {"units": "metres", "vertex_scale": 1e-5, "cluster_mm": CELL_MM, "source": args.stl.name,
               "meshes": {"registration_plate": mesh}, "layout": layout.public()}
    args.output.write_text("// Registration plate for two SO101 followers and Orchid. Generated by scripts/build_plate_visual.py.\n"
                           "// Reduced for display only.\n"
                           "(function(root){const data=" + json.dumps(payload, separators=(",", ":")) + ";\n"
                           'if(typeof module!=="undefined")module.exports=data;else root.OrchidPlate=data;\n'
                           '})(typeof window==="undefined"?globalThis:window);\n')
    print(f"{len(mesh['triangles']) // 3} triangles (from {mesh['source_triangles']}), {args.output.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
