#!/usr/bin/env python3
"""Build the locally bundled SO101 visual meshes (standard library only).

python scripts/build_so101_visuals.py --cache-dir /tmp/orchid-so101
Fetches pinned upstream CAD only if absent from the cache. Never run by the app.
"""
import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import struct
import urllib.request
import xml.etree.ElementTree as ET

REVISION = '385e8d7c68e24945df6c60d9bd68837a4b7411ae'
UPSTREAM = f'https://raw.githubusercontent.com/TheRobotStudio/SO-ARM100/{REVISION}/Simulation/SO101/'
CELL = 0.00065  # 0.65 mm vertex clustering; display only, never collision geometry.


def fetch(cache, name):
    path = cache / name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(urllib.request.urlopen(UPSTREAM + name, timeout=30).read())
    return path.read_bytes()


def simplify(data):
    count = struct.unpack_from('<I', data, 80)[0]
    if len(data) != 84 + count * 50:
        raise ValueError('Expected binary STL')
    vertices, lookup, faces = [], {}, []
    for offset in range(84, len(data), 50):
        coords = struct.unpack_from('<9f', data, offset + 12)
        face = []
        for i in (0, 3, 6):
            vertex = tuple(round(x, 7) for x in coords[i:i+3])
            if vertex not in lookup:
                lookup[vertex] = len(vertices)
                vertices.append(vertex)
            face.append(lookup[vertex])
        faces.append(face)
    buckets = defaultdict(list)
    for i, v in enumerate(vertices):
        buckets[tuple(round(x / CELL) for x in v)].append(i)
    remap, reduced = {}, []
    for indices in buckets.values():
        new = len(reduced)
        reduced.append([round(sum(vertices[i][axis] for i in indices) / len(indices) * 100000)
                        for axis in range(3)])
        for i in indices:
            remap[i] = new
    seen, triangles = set(), []
    for face in faces:
        f = tuple(remap[i] for i in face)
        key = tuple(sorted(f))
        if len(set(f)) == 3 and key not in seen:
            seen.add(key)
            triangles.extend(f)
    bounds = [[min(v[i] for v in reduced) / 100000 for i in range(3)],
              [max(v[i] for v in reduced) / 100000 for i in range(3)]]
    return {'vertices': [x for v in reduced for x in v], 'triangles': triangles, 'bounds': bounds,
            'source_sha256': hashlib.sha256(data).hexdigest(), 'source_triangles': count}


def build(cache, output):
    source = fetch(cache, 'so101_new_calib.urdf')
    robot = ET.fromstring(source)
    meshes, visuals = {}, []
    motor_for_link = dict(zip(['base_link', 'shoulder_link', 'upper_arm_link', 'lower_arm_link', 'wrist_link', 'gripper_link'],
                             ['shoulder_pan', 'shoulder_lift', 'elbow_flex', 'wrist_flex', 'wrist_roll', 'gripper']))
    for link in robot.findall('link'):
        for visual in link.findall('visual'):
            source_path = visual.find('geometry/mesh').get('filename')
            name = Path(source_path).stem
            if name not in meshes:
                meshes[name] = simplify(fetch(cache, source_path))
            origin = visual.find('origin')
            material = visual.find('material').get('name')
            visuals.append({'link': link.get('name'), 'mesh': name, 'material': material,
                            'xyz': [float(x) for x in origin.get('xyz').split()],
                            'rpy': [float(x) for x in origin.get('rpy').split()],
                            'motor': motor_for_link.get(link.get('name')) if material == 'sts3215' else None})
    payload = {'revision': REVISION, 'units': 'metres', 'vertex_scale': 0.00001,
               'cluster_metres': CELL, 'urdf_sha256': hashlib.sha256(source).hexdigest(),
               'meshes': meshes, 'visuals': visuals}
    output.write_text('// SO101 CAD, TheRobotStudio, Apache-2.0. Generated by scripts/build_so101_visuals.py.\n'
                      '// Reduced for display; see THIRD_PARTY_NOTICES.md.\n'
                      '(function(root){const data=' + json.dumps(payload, separators=(',', ':')) + ';\n'
                      'if(typeof module!=="undefined")module.exports=data;else root.OrchidArmVisuals=data;\n'
                      '})(typeof window==="undefined"?globalThis:window);\n')
    print(f'{len(meshes)} meshes, {len(visuals)} parts, {sum(len(v["triangles"])//3 for v in meshes.values())} unique triangles, {output.stat().st_size:,} bytes')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache-dir', type=Path, required=True)
    parser.add_argument('--output', type=Path, default=Path('orchid_demo/static/arm-visuals.js'))
    args = parser.parse_args()
    build(args.cache_dir, args.output)
